basePath: /
host: localhost:8000
info:
  contact:
    email: lucascoronel0597@gmail.com
    name: Lucas Coronel
    url: https://github.com/lccoronel
  description: Product API with authentication
  license:
    name: Full Cycle License
  termsOfService: http://swagger.io/terms/
  title: Go Expert API Example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
